### ISSUE TITLE
review

### ISSUE THREAD

**Issue by musvaage** [ycaseau/CLAIRE4#6]
Installed on linux the banner returns macos.

One might expect typing `q` that the software would have a newline printed when exiting.

```
$ cd /tmp
$ git clone -q https://github.com/ycaseau/CLAIRE4.git
$ mkdir -p ~/go && mv CLAIRE4/init.cl ~/go
$ rm CLAIRE4/src/*/{Core.go,Generate.go,Language.go,Optimize.go,Reader.go}
$ mv CLAIRE4/src ~/go/ && cd ~/go
$ export GO111MODULE=off && export PATH=/usr/local/go/bin:${PATH}
$ go build src/claire4.go
$ ./claire4
-- CLAIRE run-time library v 4.1.2 [os: macos, compiler:go ] --
Hello CLAIRE4, this is our init.cl file
Done. 
claire> q
eval[1]> $ 
```
https://sites.google.com/view/claire4/getting-started/tutorial

_cf_: release.cl

The output from the tutorial.

```
% claire
claire> load("release")
eval[1] true
claire> main()
eval[2] claire release 4.0.4 
claire> q
%
```

From my test there appears output with an unexpected `unknown` line.

```
$ cat << EOF > release.cl
> main() -> printf("claire release ~A\n", release())
> EOF
$ ./claire4
-- CLAIRE run-time library v 4.1.2 [os: macos, compiler:go ] --
Hello CLAIRE4, this is our init.cl file
Done.
claire> load("release")
eval[1]> true
claire> main()
eval[2]> claire release 4.1.2
unknown
claire> q
eval[3]> $ 
```

Excepting `init.cl` and `readme.cl` the same named files in meta are newer than those in src/meta.

```
$ diff CLAIRE4/meta/call.cl CLAIRE4/src/meta/call.cl | sed 4q
4c4
< //| Copyright (C) 1994 - 2021 Yves Caseau. All Rights Reserved  |
---
> //| Copyright (C) 1994 - 2013 Yves Caseau. All Rights Reserved  |
$ diff CLAIRE4/meta/init.cl CLAIRE4/src/meta/init.cl
$ diff CLAIRE4/meta/readme.cl CLAIRE4/src/meta/readme.cl
$ 
```

**Comment by xpech** [comment]
Hi, 
The banner just tel that the compiler was compiled on a Mac.

**Comment by musvaage** [comment]
> banner

```
$ ed -s ~/go/src/Core/Core-meta.go <<<'748,755p'
  ClEnv.Version = 1.2
  PRINC("-- CLAIRE run-time library v 4.")
  F_princ_float(1.2)
  PRINC(" [os: ")
  PRINC("macos")
  PRINC(", compiler:")
  PRINC("go")
  PRINC(" ] --\n")
$ ed -s ~/go/src/Kernel/ClEnv.go <<<'57'
        Osname             *ClaireString    // the name of the env "macos","win","linux",...
$ ed -s ~/go/src/Kernel/ClEnv.go <<<'156'
        ClEnv.Osname = MakeString("macos")
$ 
```

<hr>

Any insight into clarifying what encoding this file is actually in?

test/nonreg/Bug6.cl

the `file` utility returns that Bug6.cl is UTF-8 text

but on 2 lines beginning with semicolons there are illegible characters

**Comment by musvaage** [comment]
moving to U+20AC

I file my objection here to the stated intention to use that unicode character in the source code.

`https://sites.google.com/view/claire4/faq#h.z7v2ebdnfxxx`

- Set membership is %, which is ugly (and conflict with the common usage of % for modulo) but will move to €, which looks more like the mathematical symbol for membership (∈)

**Comment by ycaseau** [comment]
Hello,
a couple of answers, since there are a couple of questions/issues.
(1) duly noted for the q / exit behavior. Clearly MacOS and Linux behave differently as far as the stdoutput port is concerned.
     I need to find myself a linux machine :)
     I  had one earlier but not for the past few years

(2) the "bug*" test files have been collected over 30 years, where CLAIRE main dev env has move from Linux to Windows and Windows to MacOS. Some files have old character encodings
lines 142/144 of bug6.cl
// introduce a new char for ALI
;[�(x:integer) -> x * x]
;(check("sqr �",�(2) = 4))
is precisely a test to see if strange characters could be used .... This comes from Windows, and works on MacOS

(3) the banner is produced at cross-compile time, that means that you should recompile CLAIRE 4 on you machine to make it specific to your OS. (cf. Section (5) of the installation guide)
    -> you update init.cl (to reflect the default OS)
   -> you recompile claire4.go thanks to 
            sclaire4 -sf Generate -o claire4
This is not very friendly, I would agree, so a good suggestion to change in a future version.

(4) I am curious about why using € for membership would cause a problem. Obviously, for upward compatibility reasons, % will continue to work for membership .... but I figured that € was closer to the mathematical membership.
Also % is seen as modulo by programmers, so it is not very satisfying.

**Comment by musvaage** [comment]
time permitting

might you address the unexpected `unknown` line

> (2)

pull `#5` has some non-English strings typo corrected

personally I have not run any of the tests

> (3)

read the guide prior to setting up for installation

my initial presumption had been that detection of the OS was part of the code

> (4)

ugly, ...conflict with the common usage of % for modulo

not very satisfying

personally, I don't doubt the sincerity of those phrases

of course on my Danish laptop there exists a key combination to generate U+20AC

a close friend of mine of many years had written an epilogue to the Danish translation of the book "The New Europeans"

personally I do not sympathise with the Common Market in general as it was referred to in the early 70s

<hr>

my current circumstance allocates for a bit free time for me to fix some of the documentation

**Comment by musvaage** [comment]
maybe `Reconstruction, Binding`

```
$ grep -nr Restruction CLAIRE4 | sed 1q
CLAIRE4/compile/ocall.cl:14:// *    Part 1: Restruction Binding                                 *
$ 
```

elsewhere I've encountered the string casted but it seems to be incorrect English

```
grep -nr casted CLAIRE4
```

these may be correct, but explanations in this ticket would be welcomed

```
grep -nr appartion CLAIRE4
grep -nr reciprocately CLAIRE4
```

not sure on my end of what the replacement strings might be were these factually changed

```
grep -nr facy CLAIRE4
grep -nr holded CLAIRE4
grep -nr inded CLAIRE4
grep -n indente CLAIRE4/test/nonreg/Bug3.cl
grep -nr respections CLAIRE4
grep -nr reveived CLAIRE4
grep -nr standartd CLAIRE4
grep -nr wigh CLAIRE4
grep -nr worlf CLAIRE4
```

my presumption is this could be changed to inferred at the output locations in compile/\*.cl and src/Generate/\*.go

```
grep -nr infered CLAIRE4
```

dumped repo strings exposed these misspelled words

Cannot, Disjunctive, Instantiate, January, July, macOS, Watcom, abstract, access, address, addressable, always, ambiguous, annotates, annotation, applied, array, abstract, associated, attached, auxiliary, beginning, bootstrapping, check, compile, compiling, construction, conversion, contradiction, constraint, counter, critical, debugging, deletion, disambiguate, description, design, dictionary, dictionaries, directly, disappear, disappeared, discount, discrepancy, dispersion, distributivity, elapsed, encountered, enumeration, ephemeral, explicit, examples, expected, extended, forbidden, forbidding, guest, generate, guaranteed, global, handled, however, indentation, increments, independent, instantiation, instruction, instructions, interpreted, interpreter, initialisation, keyboard, language, little, management, managed, membership, measurable, method, mimics, multivalued, namespace, nastily, necessary, occurred, occurrence, objects, opportunity, optimization, overridden, overwritten, parameter, parameterized, position, preferred, produces, program, propagation, property, reasoning, rewrites, recursive, recursively, reentrant, reflexive, restriction, reuse, retrieve, returns, safety, search, seen, self, spaniard, special, specific, standard, stepping, strictly, structure, structures, symbols, symmetric, symmetrical, temporary, traceability, trust, uniquely, unknown, useful, variables, with, without

**Comment by musvaage** [comment]
@ycaseau

were you amenable to a pull or pulls fixing the exposed typographical errors

please inform if you prefer a limit on the number of lines changed in a single pull

**Comment by musvaage** [comment]
print U+2208
print U+222A

emacs

<kbd>C-x 8 RET</kbd> and in the echo buffer the Unicode name or <kbd>#x2208</kbd> and then <kbd>RET</kbd>
<kbd>C-x 8 RET</kbd> and in the echo buffer the Unicode name or <kbd>#x222A</kbd> and then <kbd>RET</kbd>

vim

while in insert mode

<kbd>C-k (-</kbd>
<kbd>C-k U)</kbd>

**Comment by musvaage** [comment]
> linux machine
> 
> print U+2208
> print U+222A

possibly claire on POSIX could be segregated from other bash or C shell use

by using for claire a shell with a customised keymap

es: a shell with higher-order functions

https://github.com/wryun/es-shell

XS: The eXtensible Shell

[XS](https://github.com/TieDyedDevil/XS) meson build [abandonware]

a few years ago I built it using a python3 virtual environment (venv) with meson-0.54.x and again with meson-0.56.x

see the  ./buildscan.sh  [output](https://github.com/vaerksted/XS) in a repo fork with modified README.md; guess the C++ code could be improved

[XS](https://github.com/varehus/XS) autotools build

on my Linux box for this version I had to use the variable `LIBS="-lgccpp"` before running `./configure`

<hr>

[XS-library](https://github.com/TieDyedDevil/XS-library) [abandonware]

XS-library/xs/lib.d/math.xs

a Free Software Foundation employee's comments on the foregoing

I looked at math.xs, and boy is it ugly.

In addition, it seems to mean using functional programming to decompose a list.  That is a pain in the neck.

I don't know whether it is more bad or less bad than programming in shell syntax.  But at least there' an excuse in that case: programming is built around a command line syntax.  I see no excuse for making the math.xs syntax so inconvenient.  If they're designing a new language from zero, why take such a big step backard?

**Comment by musvaage** [comment]
@ycaseau 

> sclaire4 -sf Generate -o claire4

`grep -r sclaire CLAIRE3.5`

the above returns several file names

the similar grepped for string in the CLAIRE4 cloned repo returns only the file name CLAIRE4/compile/log.cl

so in the CLAIRE4 tree I don't have any `sclaire4` file

when init.cl is modified running `claire4 -sf Generate -o claire4` will overwrite claire4.go

it is unclear what in init.cl to add or modify

where after running the above command and a recompile the banner will display the correct OS

<hr>

built claire on Windows

release.cl

at least running in Windows PowerShell

after returning `claire release 4.1.2`  also is returned on the next line `unknown`

> the q / exit

noted is that in contrast to the herein report regarding linux the  behavior is as expected

<hr>

separately is noted as no overwrite of characters occurs that claire run in "dumb" terminals is fully functional

![dumb](https://github.com/user-attachments/assets/17f6fad8-f810-420e-b717-550b3f99d54a)

**Comment by musvaage** [comment]
Running on Linux the **date!** output is different than as shown in the documentation.

```
claire> date!(0)
eval[1]> "Monday 11-04-2024 10:00:25"
claire> date!(1)
eval[2]> "Monday 11-04-2024"
claire> date!(2)     
eval[3]> "10:01:01"
claire> 
```

**Comment by musvaage** [comment]
For consistency among the community I'd probably use the same mapping as established for these keyboards.

`https://dfns.dyalog.com/n_keyboards.htm`

en-US, en-GB, da-DK, fr-FR, de-DE, es-ES, fr-BE, fi-FI, it-IT [keyboards]

What key sequence is used is another matter.

ELEMENT OF "∊" (U+2208)
UNION "∪" (U+222A)

```
  ┌────┐
  │E   │
  │€ ∊ │
  └────┘

  ┌────┐
  │V   │
  │  ∪ │
  └────┘
```

<hr>

The program could be started by a wrapper shell script which calls the alternate keyboard prior to starting claire.

**Comment by musvaage** [comment]
> One might expect typing `q` that the software would have a newline printed when exiting.

@SteveL-MSFT

Don't spend time on this, but if you have a quick explanation of the pwsh code involved perhaps you can post it.

**Linux**

exiting claire running e.g. in uxterm there is no newline printed

exiting claire running in pwsh there is a newline printed  [same as running in powershell.exe on Windows]

I am curious if you've an explanation for this behaviour?

**Comment by musvaage** [comment]
> ELEMENT OF "∊" (U+2208)
> UNION "∪" (U+222A)

Notwithstanding a sympathy for retaining the option to run CLAIRE in a "dumb" terminal.

It can be coded in elisp that a line or region is sent to another emacs buffer.

For vim there is also this plugin using for example GNU screen or tmux.

https://github.com/jpalardy/vim-slime

Send text to a target as a REPL.

Julia has approached the entering of Unicode math symbols by typing the backslashed LaTeX symbol name.

The Julia approach of course will not function in a "dumb" terminal.

**Comment by musvaage** [comment]
_cf_: version 4.1.14

@ycaseau 

I found the time to review your merged changes.

> grep -nr Restruction CLAIRE4

> grep -nr casted CLAIRE4

> grep -nr appartion CLAIRE4

> grep -nr holded CLAIRE4

> grep -nr inded CLAIRE4

`grep -n indente CLAIRE4/test/nonreg/bug3.cl`

> grep -nr respections CLAIRE4

> grep -nr reveived CLAIRE4

> grep -nr wigh CLAIRE4

> grep -nr worlf CLAIRE4

> grep -nr infered CLAIRE4

`grep -n retreive CLAIRE4/compile/gogen.cl`

`grep -n retreive CLAIRE4/src/Generate/gogen.go`

`grep -n retreive CLAIRE4/src/Generate/Generate-meta.go`

these changes from my script don't appear to have been implemented

sed -i "s/consversion/conversion/g" CLAIRE4/src/Kernel/ClString.go
sed -i "s/instanciation/instantiation/g" CLAIRE4/src/Core/method.go
sed -i "s/instanciation/instantiation/g" CLAIRE4/src/Kernel/ClReflect.go
sed -i "s/produices/produces/g" CLAIRE4/src/Generate/gostat.go
sed -i "s/recusively/recursively/g" CLAIRE4/meta/function.cl
sed -i "s/recusively/recusively/g" CLAIRE4/src/Core/function.go
sed -i "s/relexive/reflexive/g" CLAIRE4/README
sed -i "s/retreive/retrieve/g" CLAIRE4/meta/inspect.cl
sed -i "s/seach/search/g" CLAIRE4/src/Kernel/ClBag.go

earlier these were missed by me

sed -i "s/independant/independent/g" CLAIRE4/compile/log.cl
sed -i "s/instanciation/instantiation/g" CLAIRE4/meta/method.cl
sed -i "s/produices/produces/g" CLAIRE4/compile/gostat.cl

these appear to be copied from interpreter/README (deleted file)

sed -i "s/langguage/language/g" CLAIRE4/README
sed -i "s/reasonning/reasoning/g" CLAIRE4/README
