### ISSUE TITLE
github pages

### ISSUE THREAD

**Issue by musvaage** [ycaseau/CLAIRE4#9]
@ycaseau 

`github.com/ycaseau/ycaseau.github.io`

If you want to create a new repo of the above name then the files in the following could be downloaded and copied thereto.

Were you and your colleagues to prefer a different monospace font that can be accomodated for.

`https://github.com/varehus/varehus.github.io`

[index](https://varehus.github.io/)
[claire(3)](https://varehus.github.io/3/claire.html)
[claire(7)](https://varehus.github.io/7/claire.html)

<hr>

On a separate matter in this current repo would you and your colleagues consider enabling the Wiki?

**Comment by musvaage** [comment]
I hadn't considered per entry adding a right margin **method** or **slot** designation when I wrote the .html files.

Ideally CLAIRE'S methods and slots would have remained in a single file as per the claire-4-1.pdf file's **Appendix B**.

The foregoing being noted the .html files render favourably on a mobile device that has been rotated horizontally.

**Comment by ycaseau** [comment]
Hello,
I am returning to CLAIRE after two months when my job kept me too busy.
MANY THANKS for all the typo fixes. I have included them in the 4.1.14 release that will be out in a few days.
I will look how to enable the Wiki

**Comment by ycaseau** [comment]
I have create a first Wiki page
    Le samedi 2 novembre 2024 à 23:16:35 UTC+1, musvaage ***@***.***> a écrit :  
 
 


@ycaseau

github.com/ycaseau/ycaseau.github.io

If you want to create a new repo of the above name then the files in the following could be downloaded and copied thereto.

Were you and your colleagues to prefer a different monospace font that can be accomodated for.

https://github.com/varehus/varehus.github.io

Thus far are only Index and claire(7) pages.

On a separate matter in this current repo would you and your colleagues consider enabling the Wiki?

**Comment by musvaage** [comment]
> typo fixes
> included them in the 4.1.14 release

https://github.com/ycaseau/CLAIRE4/pull/7 

If the opportunity arises perhaps you'd paste the output of running `diff` on the current and 4.1.14 releases in a comment to `#7`, or if you used a patch file to implement those changes you could copy and rename that copied file to patch.txt and then upload (drag and drop) it into a comment to `#7`. 

I'd venture to guess in `#3` (Open) the following were slated for deletion 

Appropriately prior to the upcoming release that matter might be attended to.

directory

CLAIRE4\src\meta

files

CLAIRE4\src\Core\Core.go
CLAIRE4\src\Generate\Generate.go
CLAIRE4\src\Language\Language.go
CLAIRE4\src\Optimize\Optimize.go
CLAIRE4\src\Reader\Reader.go

> first Wiki page

At this point of time in the repo Settings I am comfortable with unchecking the box under Features.

☑ Wikis Loading
Wikis host documentation for your repository.

☐ Restrict editing to collaborators only
Public wikis will still be readable by everyone.

Were abuse to occur it can be reverted easily to collaborators only write authority.

**Comment by musvaage** [comment]
rendering Appendix B as a manpage was not suitable, likewise with the reformatting of that to html

this would be better formatting and fairly consistent with the .pdf of Appendix B

```html
<html>
<head>
<title>API</title>
<style>
.box {
  display: flex;
  font-family: sans-serif;
  font-weight: bold;
  justify-content: space-between;
}
</style>
</head>
<body>
<center>
<span style="font-family: sans-serif; font-size: large;"><b>CLAIRE's API</b></span>
</center>
<p>This section contains the list of all methods and (visible) slots in CLAIRE. For each method we give the signature of
the restrictions, the modules where they are defined and a brief description of their use. Methods that have a unified
semantic and multiple implementations (e.g., self_print) may be abstracted into a single method.</p>
<div class="box"><div>^</div><div>Kernel</div><div>method</div></div>
<hr>
<pre>
x:integer ^ y:integer &rarr; integer
x:float ^ y:float &rarr; float
x:list ^ y:integer &rarr; list
x:set ^ y:set &rarr; set
</pre>
<p>(x ^ y) returns x when x and y are numbers. If x is an integer, then y must be a positive integer, otherwise an error
is raised.</p>
</body>
</html>
```

<hr>

below is a quick test to check if markdown format might be used for the top level README

one change under 2. Organization is that the list of directories and subdirectories has been sorted

```md
# CLAIRE4

## 1. Content

This repository contains the code for CLAIRE4, the new release of the CLAIRE programming language based on Go.
https://en.wikipedia.org/wiki/Claire_(programming_language)

CLAIRE is 28 years old, but CLAIRE 4.0 started in September 2020.
The current version is in alpha-status. Beta status is expected this summer of 2022

CLAIRE4 now has its own Web site: https://sites.google.com/view/claire4/home

## 2. Organization

The root of this repository contains

- this README
- an InstallationGuide
- an init.cl file that you may customize to run some of the test files

This repository has the following directories

- compile:  the relexive definition of the compiler (CLAIRE files)
- docs: a few related documents about CLAIRE including the CLAIRE user guide and two old presentation about CLAIRE.
- meta:     the reflexive definition of the interpreter (CLAIRE in CLAIRE)
- src:      Go code for building CLAIRE, all subdirectories but Kernel are generated by the CLAIRE compiler
  - Kernel: contains the go source code for "microCLAIRE" : the core of the interpreter
- test:    test files for CLAIRE
  - nonreg:    old test files accumulated over the years to avoid regressions
  - perf:     a few performance benchmarks
  - rules:     classical rule-based examples

## 3. Terms of use

CLAIRE has been built by a team as an open-source project: you are free to use and redistribute the code that is found in the GitHub directory
DISCLAIMER: THE CLAIRE SOFTWARE IS PROVIDED AS IS AND WITHOUT ANY WARRANTY, INCLUDING, WITHOUT LIMITATION,
THE IMPLIED WARRANTIES OF MERCHANTABILTY AND FITNESS FOR A PARTICULAR PURPOSE.

## 4. Why Claire ?

The two presentations in the /docs directory will tell you more, but here is a short overview.

### 4.1 Why yet another language ?

4.1.1 CLAIRE is a functional object-oriented language
- CLAIRE is a full-fledged object-oriented language that inherits from SMALLTALK.
- CLAIRE is a functional language that inherits from LISP. Functional languages have regained popularity in the last 10 years, so
- CLAIRE inherits from CECILE - a specification language from the early 90s - with the aim of concision and preciseness. CLAIRE offers a higher level of abstraction than most object-oriented language

4.1.2 CLAIRE is both statically & dynamically typed with a rich type system
- CLAIRE is a fully polymorphic languages where methods may be overloaded in multiple ways, extending traditional single-inheritance class polymorphism
- CLAIRE is dynamically typed for fast prototyping and more expressive power  …A very large part of CLAIRE code fragments can be statically typed …
- CLAIRE supports second-order types

4.1.3 CLAIRE includes a number of features that makes it easier to write complex algorithms
- Set-based programming. This was more original 30 years ago than it is now, but sets and set-based expressions are first-class citizen of the CLAIRE language
- Rule-based programming. Although “production rules” have lost their appeal,
- Search tree primitives : CLAIRE provides “hypothetical reasoning”, that is the ability to create choice points and backtrack to a previous state.

### 4.2 Claire vs other interpreted language

4.2.1 Fast interpreter
CLAIRE4 is much faster than the previous CLAIRE 3.5 version. CLAIRE is now faster than Python (on average, based on a the set of performance benchmark that is included on GitHub)
The included Excel files gives an overview of the performance tests that are included in test/perf
This is ongoing work, the performance will stabilize once CLAIRE 4.0 reaches the beta status.

4.2.2 Fast compiler
CLAIRE 4.0 is also MUCH faster than CLAIRE 3.5 as a compiler.
Based on the preliminary results, CLAIRE is approximately twice slower than Go, C++ or Java, based on a weighted distribution of the performance benchmarks.

4.2.3 CLAIRE is a hybrid interpreted/compiled language: thanks to the reflective nature of CLAIRE (everything is reflexively described and is inspectable as such),

### 4.3 Claire vs Go

4.3.1 CLAIRE has interesting features that are missing from GO
- CLAIRE is interpreted 
- it supports "true" object-oriented programming
- it provides Full polymorphism
- Exception handling

4.3.2 microCLAIRE (the Go Kernel) has its own merit for anyone who plans to write an interpreter:
- Fast reflective addition to objects and functions (much faster than the mechanism provided by Go)
- Generic set objects (something that should be improved in the future when comparing with Java)
- Fast buffered character I/O
```

it seems the section & subsection numbering is not really serving a purpose so could be removed

markdown rendering absent section & subsection numbering where browser window intentionally resized

![md](https://github.com/user-attachments/assets/16809a52-d51e-4276-95dc-dedacafa85ae)

**Comment by musvaage** [comment]
@ycaseau 

> the 4.1.14 release

compile/gomain.cl
src/Generate/gomain.go
 
rather innocuous but the help file sections' last 2 listed options could have a blank space removed before the option

**Comment by musvaage** [comment]
website

Cool Samples

September 2024 update with o1-preview: still unable to solve the problem, allthough it starts with

Yes, Luke can spend exactly $150,000 on some of these items. This is a classic subset sum problem, where we need to find a combination of item prices that add up to the target sum of $150,000.

It then gives proudly a (false) solution, then finds that the sum adds up ... and concludes that the problem has no solutions !

As of January 2025 Copilot generated some Python code which when run returns an alternate set of numbers than those which the claire code on the webpage returns.

```
claire> 4208 + 980 + 5172 + 15098 + 8210 + 4148 + 7750 + 10078 + 20104 +
16130 + 12274 + 7852 + 19146 + 4150 + 9150 + 5550
eval[1]> 150000
claire> 10104 + 16368 + 18946 + 21076 + 13028 + 15098 + 20104 + 16130 + 19146
eval[2]> 150000
claire> 
```

<hr>

The Copilot generated code formatted in a flat file, and the `time` utility and python3 interpreter's outputs.

```
$ cat knapsack
from itertools import combinations

prices = [
    10104,
    8956,
    4208,
    16368,
    6106,
    18946,
    21076,
    9460,
    17190,
    23108,
    13028,
    20210,
    8844,
    5172,
    980,
    3204,
    15098,
    7188,
    4850,
    12376,
    13220,
    8210,
    12330,
    4148,
    7750,
    10078,
    20104,
    16130,
    12274,
    7852,
    19146,
    4150,
    9150,
    5550,
]
target = 150000

def find_combinations(prices, target):
    for r in range(1, len(prices) + 1):
        for combo in combinations(prices, r):
            if sum(combo) == target:
                return combo
                return None

result = find_combinations(prices, target)

if result:
    print("Luke can buy the following items to spend exactly $150,000:", result)
else:
    print("No combination of items sums up to $150,000.")
$ /usr/bin/time python3 knapsack
Luke can buy the following items to spend exactly $150,000: (10104, 16368, 18946, 21076, 13028, 15098, 20104, 16130, 19146)
8.58user 0.00system 0:08.59elapsed 99%CPU (0avgtext+0avgdata 8008maxresident)k
0inputs+0outputs (0major+851minor)pagefaults 0swaps
$

```

**Comment by musvaage** [comment]
@ycaseau 

> the 4.1.14 release

The file docs/claire-4-1.pdf seems to have gone missing.
